/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pwzjiebobxoejwdopqnx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3emppZWJvYnhvZWp3ZG9wcW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMDM5NDUsImV4cCI6MjA3NTc3OTk0NX0.3wOQlCHxddL0Q7aHj8mAdSZWNFb6hodRER7X-of-S6s"